name: Run Benchmarks

on:
  pull_request:
    paths:
      - 'graphql/*'
      - 'wrk/*'
      - 'nginx/*'
      - 'analyze.sh'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Benchmarks
      run: bash run_benchmarks.sh

    - name: Update README
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: update benchmark results [skip ci]'
